# Generated by Django 5.0.3 on 2024-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_user_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
